### ISSUE TITLE
SVG with external source not loaded for Ajax

### ISSUE THREAD

**Issue by GMOUDOND** [Keyamoon/svgxuse#1]
Thanks for this polyfill :D; i just find out that svg are not visible when a partial html is loaded with Ajax. This is also true if the external svg is already in use; the external svg content is not injected in this case.

**Comment by Keyamoon** [comment]
That's true. DOM changes were not a major concern of mine because I wanted to keep the polyfill simple and without performance issues. But I'm thinking about a solution now. A workaround for now would be to add an invisible use element to your HTML, with a link to the external SVG that you want to load.

What do you mean by an external SVG that's already in use? Could you provide an example please?

**Comment by GMOUDOND** [comment]
I don't think that workaround would fix this since the polyfill load the svgsprite in the DOM. What i meant by external svg already in use is the fact that some icon are not visible whereas they are part of the same svgsprite already loaded in the DOM; icons loaded on window.load are all ok. The only difference is Ajax.

**Comment by Keyamoon** [comment]
Okay, I now see what you mean regarding an SVG already in use. Any new use elements added to DOM should be visible. It would be a browser bug if they don't. And I can't reproduce this issue either:

http://jsbin.com/tezesufaxo/edit?html,js,output

In the reduced test case above, I'm simulating what you suggested. But it works fine in Chrome, Firefox and Safari. Even if it doesn't, it would be a browser bug.

Am I missing something here?

**Comment by idready** [comment]
Here is what i meant: http://codepen.io/idready/pen/MaxgMq?editors=101
I'm really getting frustated since this work.
I will double check tomorrow and let you know.

I'm testing on IE9+ (particularly on IE11).

**Comment by Keyamoon** [comment]
@idready Hmm, your demo doesn't seem to add any SVG (with use element) to the DOM. But nevertheless, svgxuse doesn't currently work when SVGs are dynamically added to the page. I'm working on a solution though.

**Comment by idready** [comment]
I just update the demo and added a text; the svg is added dynamically.

**Comment by GMOUDOND** [comment]
I found a temporary workaround for IE9+; i changed the IIFE and instead return the function to make sure i can be called manually; i will PR this asap.
Here are others improvements i will add with the PR:
- Make sure the sprite is not injected twice or more
- Maybe make a return for manual call only for IE?
- Fix "body.insertBefore" which reference as null on IE (seen on IE10)

Let me know if you are already on something here.

**Comment by Keyamoon** [comment]
I was thinking about using mutation observers and mutation events to detect changes to DOM.

The cache variable prevents SVGs from being added multiple times. But yes if you call the function again, it would lose its purpose; unless it's moved to the parent scope.

I haven't seen any issues with insertBefore in IE10. In my tests, IE10 was working fine.

**Comment by GMOUDOND** [comment]
For IE10 i will check again before the PR. The polyfill is really good for perf compared to svg4everybody on IE, the only problem is the DOM change issue.

**Comment by Keyamoon** [comment]
We'll have to try both approaches of exposing a function and watching for changes. If watching for changes doesn't have a bad impact on performance, it would be a better solution. It's not always possible or easy to call a function when the DOM dynamically changes. Especially if you are using a framework. So I'm not sure if exposing a function would be an optimal solution. But I did consider it too.

**Comment by GMOUDOND** [comment]
Ok. Have this in mind for mutationobserver : http://caniuse.com/#feat=mutationobserver

**Comment by Keyamoon** [comment]
Yes, I'm aware of that. I'll try mutation events (instead of observers) in order to support IE 9 and IE 10.

**Comment by Keyamoon** [comment]
Here's the solution I've been working on: https://github.com/Keyamoon/svgxuse/tree/observe-dom-changes (The demo has not been updated yet because it depends on bower.)

I'm going to test it more thoroughly before merging. Your feedbacks would be appreciated.

**Comment by GMOUDOND** [comment]
Count on me. I will check that asap.

**Comment by idready** [comment]
I made a PR, tested on IE10+, Chrome 46 and FF 42. Comments on the code. The PR is made from DOm-Observe-Change branch. Only one file was modified.

**Comment by Keyamoon** [comment]
@idready Yes. I saw that. And I commented on it as well.

**Comment by Keyamoon** [comment]
v1.1.0 was released. Should fix issues with ajax or dynamic changes to dom in general.
