### ISSUE TITLE
svg not showing with reset stylesheet

### ISSUE THREAD

**Issue by claudia-romano** [Keyamoon/svgxuse#11]
Hi, thanks for the polyfill!
I was testing it on the demo file downloaded from IcoMoon. As soon as I include a reset stylesheet (to reset body margin), the svg icons are not visible anymore. Here's a test case (tested on IE11):
http://ambercreative.co/external-svg/  

Thanks!

**Comment by Keyamoon** [comment]
Hi,

Thanks for reporting this issue. Should be fixed now. IcoMoon was updated as well. You may refresh it and try again.

**Comment by claudia-romano** [comment]
Thank you!
