### ISSUE TITLE
Hidden svg is not loaded when becoming visible due to css media queries

### ISSUE THREAD

**Issue by episource** [Keyamoon/svgxuse#12]
# Description

Hidden svg is not loaded when becoming visible due to css media queries.

**Steps to reproduce:**
    1. Display the following html page in IE11 or any browser requiring svgxuse polyfill and make sure the window is wider than 840px

```
<!DOCTYPE HTML>
<html>
<head>
    <style>
        #test {
            display: none;
        }

        @media screen and (max-width: 840px) {
            #test {
                display: block;
                background-color: red;
            }
        }

    </style>
</head>
<body>
    <svg id="test"><use xlink:href="/path/to/sprite.svg#someId"></use></svg>
    <script type='text/javascript' src='/assets/js/svgxuse.js'></script>
</body>
</html>
```

```
2. reduce window size below 840px
```

**Expected behavior:** The svg becomes visible in front of a red background.
**Observed behavior:** A red bar without svg.
# Analysis

Since 493bc89be5b693e7ff22d7f219562268563cdec8, svgxuse doesn't load hidden sprites. A MutationObserver is used to detect DOM changes and trigger a (delayed) svg use check. The MutationObserver can detect when new svg use nodes are added dynamically or when previously hidden elements are shown by javascript code changing attributes (e.g. class). However, as far as I know, the MutationObserver can't detect (computed) style changes caused by media queries.

**Comment by Keyamoon** [comment]
Thanks for reporting this issue. It's probably mainly an issue for developers. End users rarely resize their windows back and forth like we do! Nevertheless, it should be fixed.

I'm thinking about listening to window resize events (debounced) for fixing this issue.

**Comment by Keyamoon** [comment]
v1.1.8 fixed this issue. Please verify if it works for you.

**Comment by episource** [comment]
Works fine with v1.1.9.
