### ISSUE TITLE
Inserted svg node not hidden properly

### ISSUE THREAD

**Issue by episource** [Keyamoon/svgxuse#14]
#13 addressed the issue, that inserted svg nodes hidden by setting width and height to zero, were still displayed by IE.

The solution has been setting `visibility: hidden` on the inserted svg node. This prevents the svg node from being rendered, nevertheless IE11 and Windows Mobile 8 IE evaluate the svg's intrinsic width and display unwanted scrollbars. Have a look at [this example](http://jsbin.com/saqilesoyo/1/edit?html,output) with IE or the screenshots below (top: IE with scrollbar; below: firefox renders as expected).

![svgxuse_inserted_svg_scrollbar](https://cloud.githubusercontent.com/assets/3219567/13371861/618e4026-dd30-11e5-8162-6fcae43de1b8.jpg)

```
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width">
</head>
<body>
<svg style="position: absolute; width: 0; height: 0; visibility: hidden" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>Test image</title>
    <defs>
        <symbol id="icon" viewBox="0 0 100 100">
            <title>rect</title>
            <rect width="100%" height="100%" fill="red"/>
        </symbol>
    </defs>
    <text x="5" y="20" style="font-size:15">This text is shown when viewing the svg file directly... Some more characters to make this text wider: abcdefghijklmnopqrstuvwxyz</text>
</svg>

<svg style="width:25px; height:25px;"><use xlink:href="#icon"></use></svg>

</body>
</html>
```

Setting `display: none` is no viable solution as it breaks gradients. This has been discussed in #13. 

I tried using `position: fixed` instead of `position: absolute` for the inserted svg node. This worked for me, but I'm unsure about possible side effects.

**Comment by Keyamoon** [comment]
Thanks. I opted for using `overflow: hidden`. Should have used it in the first place!

Your solution works too. I don't think there are any side effects to using fixed positioning; other than perhaps performance issues.

**Comment by episource** [comment]
> Thanks. I opted for using overflow: hidden. Should have used it in the first place!

Obiously the best solution. Works like a charm. Thanks a lot!
