### ISSUE TITLE
SVG tag is added even in Chrome and Safari

### ISSUE THREAD

**Issue by seleckis** [Keyamoon/svgxuse#15]
Svg is insearted in body tag in Chrome and Safari browser, not only IE.
![screen shot 2016-03-11 at 17 30 08](https://cloud.githubusercontent.com/assets/988504/13706743/0639cd88-e7af-11e5-9200-494d5035ff9c.png)

**Comment by Keyamoon** [comment]
That can have different reasons. For example, if you are referencing an external SVG without proper CORS headers, modern browsers like Chrome or Safari would fail to load the SVG, but svgxuse detects that and loads the SVG.

In other cases, svgxuse may detect empty SVGs and send its request before or at the same time as the browser. In these cases, if you look at the network tab in Chrome, you should see that one of the requests gets canceled. In other words, there won't be any redundant requests.

That being said, I added a delay to the initial checking of the DOM to prevent this issue when the SVG has not been cached yet.

**Comment by seleckis** [comment]
Thank you for your answer, but it seems nothing changed. SVG tag is still there.

**Comment by seleckis** [comment]
BTW, Firefox has SVG tag also

**Comment by seleckis** [comment]
I've found a problem: If any of "svg use" constructions in html is trying to link to non existing anchor in svg file, your script will put svg tag into body.

**Comment by Keyamoon** [comment]
So if you don't link to non existing ones it works fine?

**Comment by seleckis** [comment]
yes. But…
I cannot understand what is happening. Please take a look: http://www.thealuminiumstory.com/
In Safari works fine.
In Chrome puts svg into body.
In Edge puts svg into body.
In Firefox puts svg into body only, if cursor is not placed over illustration on load.

I checked all links. Everything should be correct.

**Comment by Keyamoon** [comment]
When you link to a non-existing glyph definition, your SVG would be empty. Therefore, the polyfill adds detects a problem, sends a request and prepends the SVG to the body. It makes sense and I don't see any problem with that.

It's hard to figure out what's going on on that page. Please provide a reduced test case instead.

**Comment by seleckis** [comment]
I found! If I use transform: scale(0,0); script thinks that svg image cannot load.

**Comment by Keyamoon** [comment]
Makes sense. This is just how svgxuse works. It checks whether the `use` element is hidden. If it's hidden, it would add the SVG.

Again, even if it adds the SVG, if you look at the network tab in Chrome, you would notice that one of the requests for the external SVG file would  get canceled. So there are no downsides here. Your page should look and work the same.

**Comment by Keyamoon** [comment]
See v1.1.12.

**Comment by seleckis** [comment]
Thank you for update. But you forgot to deny rewriting values of xlink:href attributes in this case. Only for hidden svg.

**Comment by Keyamoon** [comment]
Thanks for the heads-up. Fixed.

**Comment by seleckis** [comment]
Now it works perfectly in all browsers except Edge. SVG tag still appears there.

**Comment by Keyamoon** [comment]
Does the version of Edge you're using support referencing external SVGs?

**Comment by seleckis** [comment]
I tried on virtual machine on Windows 10 provided by modern.ie. It works perfectly on native Windows 10/Edge. Thank you very much! Great job!

**Comment by Keyamoon** [comment]
Okay. Good to know. I guess we can close this issue now?
Maybe the modern.ie version was older? Did you compare the exact version numbers?

**Comment by seleckis** [comment]
Yes, close this issue.
Versions are different:  Edge 20.10240.16384.0 vs 25.10586.0.0.

**Comment by Keyamoon** [comment]
Thanks for the info.

**Comment by seleckis** [comment]
JFYI, if svg tag in svg file has no attribute xmlns="http://www.w3.org/2000/svg", script also will add svg into body in any browser.
