### ISSUE TITLE
Demo files on server didn't work on IE9

### ISSUE THREAD

**Issue by Matthieusch** [Keyamoon/svgxuse#16]
Hi,

I wonder why I can't make it work on IE9.
Maybe this screenshot can help you understand my problem :
![image](https://cloud.githubusercontent.com/assets/5374314/13711549/6cab28a4-e7bf-11e5-9e48-37bd12d14461.png)

Am I doing something wrong?

Regards,
Matthieu

**Comment by Keyamoon** [comment]
Please provide a reduced test case. The live demo works fine in IE9+: https://icomoon.io/svgxuse-demo

**Comment by Matthieusch** [comment]
Thanks for the quick answer ! :+1: 

Yes the live demo works fine, is there any important CSS rules to create ?
I used icomoon to generate my `symbol-defs.svg` but I can't make it work on IE9 for some reasons, IE>9 works just fine.

Here is my HTML declaration :

```
<svg class="informations__icon" width="20" height="20">
<use xlink:href="/folder/folder/symbol-defs.svg#svg-informations__element--phone"></use>
</svg>
```

and CSS rules attached to informations__icon :

```
.informations__icon {
  display: block;
  margin: 0 15px 0 0;
}
```

**Comment by Keyamoon** [comment]
See this:  https://dl.dropboxusercontent.com/u/38300086/svgxuse-demo/index.html

I simply put the demo that IcoMoon generates on dropbox. Works fine in IE9. There are no special server config requirements.

**Comment by Keyamoon** [comment]
I just noticed that you're not exactly using the demo file that IcoMoon generates. When you download an SVG pack from IcoMoon, it comes with a `demo-external-svg.html` file. Did you try that on the server?

**Comment by Matthieusch** [comment]
SVG pack works fine on dropbox, but when I put it on my production server it didn't.
Must be something on the server. Sorry to bother with this issue.

**Comment by Matthieusch** [comment]
Hi @Keyamoon ! I found what was wrong on my server. :)

> **XDomainRequest**: The requested URL's server must have the Access-Control-Allow-Origin header set to either all ("*") or to include the origin of the request.

Et voilà ! Now it's working like a charm !

**Comment by Keyamoon** [comment]
@Matthieusch Good to know.
