### ISSUE TITLE
Add aria-hidden="true" to injected SVG element

### ISSUE THREAD

**Issue by fvsch** [Keyamoon/svgxuse#17]
Hi,

There is a slight risk that a screen reader would attempt to read the content of the injected `<svg>` element. Two ways to prevent that:
1. Use `display:none` for hiding the element. Given the styles currently used for hiding, I suspect that `display:none` might break stuff in some polyfilled browsers?
2. Add `aria-hidden="true"` to the element.

I'd go with #2 if you don’t want to risk any regression.

**Comment by Keyamoon** [comment]
Hi,

That's a good point. I added the `aria-hidden` attribute. Thanks for the feedback.
