### ISSUE TITLE
help wanted: Fail to load icons in Internet Explorer 9

### ISSUE THREAD

**Issue by 7opsecret** [Keyamoon/svgxuse#18]
**Summary:**
- Works on IE10 (Win 8) & IE 11 (Win 8.1) Both working fine. 
- [Demo link](https://icomoon.io/svgxuse-demo/) works on IE9 however demo folder that supplied (https://github.com/Keyamoon/svgxuse/tree/master/demo) failed to work on IE9.
- No error messages thrown on console.

**Failed on:**
- Browser: Internet Explorer 9 (Window 7) 
- Browser Mode: IE9
- Document Mode: IE9 Standards
- VM: Virtual Box 5.0.6
- Base Operating System: Mac OSX 10.10.5

**Tested environment:**
run with gulp-connect - http://localhost:8080/demo/index.html

**Comment by Matthieusch** [comment]
Hi @c-wei!
I had the same problem with Apache server instead of a gulp-connect.
Don't know if that can help you, but here is the solution which worked for me : 

> **XDomainRequest**: The requested URL's server must have the Access-Control-Allow-Origin header set to either all ("*") or to include the origin of the request.

Hope it'll help!

**Comment by 7opsecret** [comment]
Hi @Matthieusch - I was hoping if you don't mind to explain a bit more details. I wasn't quite sure what does that mean. Cheers

Edited: Thanks for the tips! i did some research and found [this solution](https://github.com/AveVlad/gulp-connect/issues/100#issuecomment-96078162). Correct me if i'm wrong, i need to apply 'Access-Control-Allow-Origin header set to either all ("*") or to include the origin of the request' configuration to the server.

**Comment by Matthieusch** [comment]
Exactly:

> apply 'Access-Control-Allow-Origin header set to either all ("*") or to include the origin of the request' configuration to the server

Cheers
