### ISSUE TITLE
Inconsistent results when svg is hidden on page load

### ISSUE THREAD

**Issue by sword** [Keyamoon/svgxuse#21]
Summary:
The **getBoundingClientRect()** left/right/top/bottom==0 check (line 140), which I assume is checking for IE (9,10,11) failure in loading external assets, also fails if the icons are deliberately hidden by CSS on page load (e.g. display:none on a parent element), and therefore disrupts svg use in non-IE browsers too.

Details:
Due to the **isHidden** check, which uses the results from **getBoundingClientRect**(), if the icons are hidden by default (i.e. a favouriting (heart) icon that only shows due to _:hover_ over each image), this code only fires when the first (due to the **MutationObserver**, or EventListener on **DOMSubtreeModified**) :hover occurs. **checkUseElems**  is called a second time from **debouncedCheck**, but the other icons on the page with identical _< use xlink:href >_ are still hidden, so still don't get modified. **unobserveChanges** is then called, so further _:hover_ events no longer trigger this functionality.

Chrome Canary (51.0.2704.103 (64-bit)) on Mac
Safari Version 9.1.1 (11601.6.17)
svgxuse@1.1.18

**Comment by Keyamoon** [comment]
I couldn't reproduce the issue. Please provide a reduced test case.

**Comment by sword** [comment]
https://gist.github.com/sword/e1efa04627153901ad911b5d1f44bd3e

The underlying cause was a broken svg file, missing the **xmlns** attribute; this caused Chrome & Safari to fail to load the remote svg, so getBoundingClientRect() returned zeros. Subsequent triggering of a DOM change only inlines the SVG if it's currently hovered (i.e. visible). A valid SVG file makes Chrome/Safari work correctly (not bother), but I guess this will continue to affect IE ( tested/confirmed bug on Win7 Enterprise VM with IE11).

However, I'm wondering if attrUpdateFunc should modify all matching < use xlink:href >, not just the current one, otherwise future uses of the same cache[spec.base] are ignored.

**Comment by Keyamoon** [comment]
Thank you. I made some changes to update all `use` elements with a matching `xlink:href`. However, if there are no DOM mutations after the document loads, and the `display` property only changes via CSS, the referenced SVG won't be loaded at all.
