### ISSUE TITLE
Firefox issue when testing with Browserstack

### ISSUE THREAD

**Issue by deverin** [Keyamoon/svgxuse#22]
Strange behaviour when testing with Browserstack

All browsers are working properly with this polyfill, but Firefox.

Locally testing with natively installed firefox in the system - OS X El Capitan - is just fine, but within Browserstack environment stuff is not working. Only with firefox and as on Windows so on OS X and different os versions. 

Tested firefox versions from 40 to 49 Aurora

Possible issue or just a false positive?

**Comment by Keyamoon** [comment]
Hmm, I have tested Firefox on both Windows and OS X. Not sure what could be causing the problem in Browserstack. Can you check your the browser's console? Are you seeing any issues in the [online demo](https://icomoon.io/svgxuse-demo)?

**Comment by Keyamoon** [comment]
No updates on this?
