### ISSUE TITLE
Unable to render the icons in chrome 

### ISSUE THREAD

**Issue by sudarshanReddykurri** [Keyamoon/svgxuse#24]
It seems the Polyfill had an issue with the latest version of chrome (Version 52.0.2743.116 m). I encountered this problem and unable to render the icons on the screen but it worked in the latest version of Firefox.
HTML FILE:
index.html

``` <html>
    <head>  
    <script src="svgxuse.js" defer></script>
   </head>
    <body>  
    <svg>   
        <use xlink:href="myicons.svg#arrow"/>
    </svg>
    </body>
    </html>
```

External SVG file:
myicons.svg

```
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      <symbol viewBox="0 0 32 32" id="arrow">
          <title>Arrow</title>
          <path fill="#0f0f0f" d="M16,0C7.2,0,0,7.2,0,16s7.2,16,16,16s16-7.2,16-16S24.8,0,16,0z M22.8,13.6l-6,8C16.6,21.9,16.3,22,16,22 s-0.6-0.1-0.8-0.4l-6-8c-0.2-0.3-0.3-0.7-0.1-1S9.6,12,10,12h12c0.4,0,0.7,0.2,0.9,0.6S23,13.3,22.8,13.6z"></path>
      </symbol>
  </svg>
```

**Comment by Keyamoon** [comment]
I don't see any issues in that version of Chrome.

Chrome doesn't even require the polyfill to begin with. So if your icon doesn't render without the polyfill, something else must be going wrong.
