### ISSUE TITLE
IE - Update

### ISSUE THREAD

**Issue by DevCarlosAugusto** [Keyamoon/svgxuse#25]
When updating the page in IE, script not working,  icons don't show. Tested in IE 11 mobile.

**Comment by Keyamoon** [comment]
Are you seeing this issue in the [online demo](https://icomoon.io/svgxuse-demo)?

Can you provide a reduced test case?

**Comment by DevCarlosAugusto** [comment]
No. I have a page and when restart it in IE mobile(windows phone), 'svgxuse' not work correctly. I don't know why.

**Comment by Keyamoon** [comment]
Closing for now due to lack of info. Feel free to reopen this issue when you have a [reduced test case](https://css-tricks.com/reduced-test-cases/).
