### ISSUE TITLE
Support href without xlink

### ISSUE THREAD

**Issue by sebpettersson** [Keyamoon/svgxuse#27]
Since SVG 2, xlink:href has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href). It'd be nice if svgxuse supported href without the xlink namespace.

Note that IE9+ actually [supports href without xlink](https://twitter.com/LeaVerou/status/780859381814587393?lang=ca).

**Comment by Keyamoon** [comment]
I just added support for `href`.

**Comment by jaydenseric** [comment]
@Keyamoon heads-up that this is broken in Safari - `use` with `href` and not `xlink:href` fails to render.

**Comment by Keyamoon** [comment]
@jaydenseric Thanks. I didn't know that. Do you think svgxuse should address this issue or should we just wait until Safari supports `href`?

**Comment by jaydenseric** [comment]
I can't find anything on Safari support for SVG 2.0 style `<use href="#foo" />` in Google. [Here](https://bugs.webkit.org/buglist.cgi?short_desc=use%20href&query_format=advanced&short_desc_type=allwordssubstr&component=SVG&product=WebKit) is a webkit bugzilla advanced search.

If it is possible to polyfill Safari that would be super.

**Comment by dartzki** [comment]
@Keyamoon for backwards compatibility we started setting both 'xlink:href' and 'href' on the <use> Element. This works for all Browsers, since the ones that support 'href' use it and those that don't use 'xlink:href'. However your script only ever updates one or the other which leads to icons not being loaded on IE11 - Is there a reason for not updating both if both are defined on the Element?

**Comment by Keyamoon** [comment]
@jaydenseric v1.26 should address the issue in Safari. It should also resolve the issue mentioned above by @dartzki. With this version, you could only set `href` and the polyfill would add `xlink:href` for you when the browser fails to render the SVG (e.g. in Safari). If you set both `href` and `xlink:href`, both attributes will get updated if necessary.
