### ISSUE TITLE
Incompatibilities with Safari (MacOS & iOS)

### ISSUE THREAD

**Issue by marius-klocke** [Keyamoon/svgxuse#30]
Some icons do not load on Safari. See javascript error on screenshot.

![screen](https://cloud.githubusercontent.com/assets/22492389/22921448/13453c78-f29a-11e6-9c6b-cec582c635e7.JPG)

![screen-ios](https://cloud.githubusercontent.com/assets/22492389/22921537/6db758d0-f29a-11e6-931b-6ce87ed9962b.JPG)

Tested on: Browerstrack with iPhone 6S (iOS 9) and Safari 8 on MacOS Yosemite.

**Comment by Keyamoon** [comment]
I was using `href` instead of `xlink:href` for some of the icons in the [demo page](https://icomoon.io/svgxuse-demo/). It turns out Safari doesn't support `href`. I just updated the demo.

**Comment by marius-klocke** [comment]
Thanks for your quick feedback. It is working for me now.
