### ISSUE TITLE
CORS issue using SVG sprite on external domain

### ISSUE THREAD

**Issue by exslim** [Keyamoon/svgxuse#31]
I'm trying to load SVG sprite from external domain and getting multiple error messages in Chrome's console:

`Unsafe attempt to load URL http://secondary.domain/sprites/defs/svg/sprite.defs.svg from frame with URL http://main.domain/. Domains, protocols and ports must match.`

I believe it's chrome related [1]. But the last console error is somewhat different 
`XMLHttpRequest cannot load http://secondary.domain/sprites/defs/svg/sprite.defs.svg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://main.domain' is therefore not allowed access.` It comes from svgxuse.

Apparently it looks like CORS issue, but external domain has right CORS headers:
`curl -I http://secondary.domain/sprites/defs/svg/sprite.defs.svg`

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 27 Feb 2017 19:27:02 GMT
Content-Type: image/svg+xml
Content-Length: 84164
Last-Modified: Mon, 27 Feb 2017 15:14:32 GMT
Connection: keep-alive
Expires: Tue, 27 Feb 2018 19:27:02 GMT
Cache-Control: max-age=31536000
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD
Cache-Control: public, max-age=315360000
Accept-Ranges: bytes

What's wrong with this setup? Thanks!

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=470601

**Comment by Keyamoon** [comment]
See if you have the same issue with this: https://icomoon.io/svgxuse-demo/symbol-defs.svg

It works fine for me.

**Comment by exslim** [comment]
svgxuse is indeed able to download SVG sprite. Loading issue was caused by aggressive browser caching. 

In the end, SVG icons are showing up, though Chrome related errors is still there - dozen of `Unsafe attempt to load URL https://icomoon.io/svgxuse-demo/symbol-defs.svg from frame with URL http://main.domain/. Domains, protocols and ports must match.` Obviously, external URL in xlink:href triggers this. Is there any workaround for this, besides of local domain?

P.S. Perhaps, fallback to `data-href` on <use> element could be temporary fix for Blink based browsers?

**Comment by Keyamoon** [comment]
As far as I know, there's no workaround to prevent that error except for using relative paths.
