### ISSUE TITLE
Base URL stripped for hidden icons

### ISSUE THREAD

**Issue by okoell** [Keyamoon/svgxuse#32]
I had a situation where initially hidden icons are being stripped of their base URL, although running in a browser that supports external SVG files (Chrome).

To reproduce it using the svgxuse demo files:

- change the hash of the first SVG icon (icon-couch) to a non-existing symbol, e.g.:
`<use href="symbol-defs.svg#icon-unknown">`
  
- make the container of the second SVG icon (icon-palette) hidden (`display: none`).

When the modified page is loaded, the href of the hidden icon is stripped of it's base URL immediately in the main loop iterating all use elements. The icon will not display when it's container is made visible later.

Admittedly this a rather contrived situation, but one that can easily be fixed by deferring the second invocation of `attrUpdateFunc` with `setTimeout` (line 209) just like it's done with the first invocation (line 175). This fixes my use case and shouldn't do any harm, as far as i can see.

Also: the second invocation of `attrUpdateFunc` is missing the `isXlink` parameter, which it shouldn't in my opinion.

Cheers

**Comment by Keyamoon** [comment]
You're right about the missing `isXlink`. Thank you.

Trying to reproduce the issue, when I make the container visible, the icon appears as expected. `svgxuse` would only remove that base URL after prepending symbol definitions to `<body>`.

**Comment by okoell** [comment]
No, the base URL is removed right away, because it's not deferred.

I'd like to attach my modified HTML but Github doesn't allow me to. So instead I'm inlining the fragment of your demo page where the icons are defined. My modification are described above.

```html
<div id="set" class="clearfix mhl ptl">
    <h1 class="mvm mtn fgc1">Grid Size: 20</h1>
    <div class="glyph fs1">
        <div class="clearfix pbs">
            <svg class="icon icon-couch"><use href="symbol-defs.svg#icon-unknown"></use></svg><span class="mls"> icon-couch</span>
        </div>
    </div>
    <div class="glyph fs1" style="display:none">
        <div class="clearfix pbs">
            <svg class="icon icon-palette"><use href="symbol-defs.svg#icon-palette"></use></svg><span class="mls"> icon-palette</span>
        </div>
    </div>
    <div class="glyph fs1">
        <div class="clearfix pbs">
            <svg class="icon icon-tornado"><use xlink:href="symbol-defs.svg#icon-tornado"></use></svg><span class="mls"> icon-tornado</span>
        </div>
    </div>
    <div class="glyph fs1">
        <div class="clearfix pbs">
            <svg class="icon icon-paper-plane"><use xlink:href="symbol-defs.svg#icon-paper-plane"></use></svg><span class="mls"> icon-paper-plane</span>
        </div>
    </div>
</div>
```

**Comment by Keyamoon** [comment]
Yes, the base URL gets removed, but it doesn't matter, because it only gets removed after symbol definitions are added to `<body>`. See this temporary link: https://icomoon.io/svgxuse-demo/index2.html

If you use Chrome's element inspector and remove the style attribute (`display: none`) from the second container, the icon would appear as expected.

**Comment by okoell** [comment]
Ah, I see. But I still disagree :)

First: the SVG shouldn't be inlined - because Chrome. But this is perhaps another story.

Second: the situation changes when there another valid icon following the hidden one. You can try it here: http://quimby.de/svgxuse/

What happens is, that the scheduled XHRequest is aborted after the base URL is removed from the hidden icon. So, no inline SVG and the hidden icon is broken when made visible.

As I said, this is really an absurd case. But it's fixed when the `attrUpdateFunc` is deferred using `setTimeout`. And I can see no harm in doing that.

**Comment by Keyamoon** [comment]
Makes sense now. Thanks for the clarification and for taking the time to report this issue.

**Comment by okoell** [comment]
My pleasure. Thank you for listening and for providing svgxuse.

Regards, Oliver


> Makes sense now. Thanks for the clarification and for taking the time to report this issue.
