### ISSUE TITLE
Can the process be envoked post load?

### ISSUE THREAD

**Issue by danciupuliga** [Keyamoon/svgxuse#39]
I am facing a scenario where some DOM elements are destroyed/created again (without being loaded via ajax). On initial load SVGs show up correctly. After being destroyed and created again, the icons disappear. 

I noticed that after inital load/scan, the event listeners are disabled via UnobserveChanges() https://github.com/Keyamoon/svgxuse/blob/master/svgxuse.js#L136 . Is there any global method I can call to rescan the DOM after the new content was created?

**Comment by Keyamoon** [comment]
https://github.com/Keyamoon/svgxuse/blob/master/svgxuse.js#L215 would make it observe changes again. So there's no need for manually calling it.

If you can provide a reduced test case that can replicate the issue, I'll take a look.

**Comment by danciupuliga** [comment]
Closing as I cannot reproduce this in a sandboxed test case which makes me believe the Dom manipulation observer is somehow getting unbound by other external code.
