### ISSUE TITLE
x.firstChild might be an XML declaration

### ISSUE THREAD

**Issue by tylersticka** [Keyamoon/svgxuse#4]
This is a great polyfill! Love the simplicity, performance and how it avoids injecting SVG elements repetitively into markup. Really well-done! :clap: 

One minor nit I'd pick is that the script assume's the external file's first element will be `<svg>`. This means that SVG files including an XML doctype declaration get that injected instead:

```
<?xml version="1.0" encoding="utf-8"?>
```

Maybe `x.querySelector('svg')` or `x.getElementsByTagName('svg')[0]` could be used instead?

**Comment by Keyamoon** [comment]
Good catch!

`x.getElementsByTagName('svg')[0]` would [probably be faster](https://www.nczonline.net/blog/2010/09/28/why-is-getelementsbytagname-faster-that-queryselectorall/).

**Comment by Keyamoon** [comment]
Thanks a lot for your kind words and for looking into the code to find this issue.

**Comment by tylersticka** [comment]
Awesome, thanks so much for updating so quickly!
