### ISSUE TITLE
Unable to get value of the property 'split': object is null or undefined

### ISSUE THREAD

**Issue by ramijarrar** [Keyamoon/svgxuse#5]
See https://github.com/jonathantneal/svg4everybody/issues/78 for a more detailed description of this issue.

Essentially `.getAttribute("xlink:href")` (and setAttribute) will not work when using certain dynamic templating libraries - a fallback to `.getAttributeNS('http://www.w3.org/1999/xlink', 'href');` when this happens should solve this.

**Comment by Keyamoon** [comment]
Thanks for reporting this issue. As you mentioned, using `getAttributeNS` and `setAttributeNS` should solve it.

**Comment by ramijarrar** [comment]
I did some more reading into this and it looks like the namespace-aware DOM methods are a safer option in all cases (see [here](http://stackoverflow.com/questions/6893391/adding-image-namespace-in-svg-through-js-still-doesnt-show-me-the-picture/6902768#6902768)). Can you add a fix for this?

**Comment by Keyamoon** [comment]
@ramijarrar Yes, that's what I guessed to be the case as well. I just need to test it to make sure it won't cause any issues in IE. I will make a commit soon.

**Comment by ramijarrar** [comment]
:+1:

**Comment by Keyamoon** [comment]
svgxuse was updated. Thanks again for reporting this issue.
