### ISSUE TITLE
The svg file is inserted twice

### ISSUE THREAD

**Issue by ghost** [Keyamoon/svgxuse#7]
Thanks for this lib.
I am using your lib to solve the problem that IE can't load external svg content, and it works. But it seems not perfect. After the page loaded, the 'onload' function is excuted twice. As a result, there are two svg elements in the body.

**Comment by Keyamoon** [comment]
I tested the [demo page](https://icomoon.io/svgxuse-demo) in IE 9 and IE 10 but can't reproduce this problem. Where did you see this issue? Can you provide a reduced test case?

**Comment by ghost** [comment]
I'm sorry It can't be reproduced now. Maybe it was my code bug.
Thanks.

**Comment by DotCoyote** [comment]
Currently got the same problem on https://www.cr-bericht.telekom.com/site17/ with IE11

**Comment by DotCoyote** [comment]
OK, this happens when you use different sprite-files
