### ISSUE TITLE
hiding the injected svg

### ISSUE THREAD

**Issue by thomasmattheussen** [Keyamoon/svgxuse#8]
I was just trying to use this polyfill, but I noticed that the injected svg is not hidden by default?

I checked out the demo page where the problem was absent, but then I saw that symbol-defs.svg had hardcoded style="position: absolute; width: 0; height: 0;". 
This seems kind of weird to me. Shouldn't the polyfill hide it with javascript before adding it to the page?

At the least it should be documented...

Unless I'm missing something here?

**Comment by Keyamoon** [comment]
That's a good point. Thanks for opening this issue. I'll make the polyfill hide the SVG before adding it.

**Comment by Keyamoon** [comment]
Should be fixed now. Thanks again for reporting this issue.

**Comment by thomasmattheussen** [comment]
Thanks! :)
